apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: nasos
    app.kubernetes.io/part-of: nasos
    pod-security.kubernetes.io/enforce: privileged
