package shares

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"hash/fnv"
	"os"
	"strings"
)

// GenerateSambaConfig generates a Samba (smb.conf) configuration for all SMB shares.
func (m *Manager) GenerateSambaConfig() string {
	var sb strings.Builder

	sb.WriteString("[global]\n")
	sb.WriteString("   workgroup = NASLOS\n")
	sb.WriteString("   server string = Naslos\n")
	sb.WriteString("   security = user\n")
	// Advertise the same name that the serving container publishes over
	// mDNS/WSD, so browsing clients and direct connections agree.
	if name := m.NetBIOSName(); name != "" {
		sb.WriteString(fmt.Sprintf("   netbios name = %s\n", name))
	}
	sb.WriteString("   map to guest = Never\n")
	sb.WriteString("   server min protocol = SMB3\n")
	sb.WriteString("   smb encrypt = desired\n")
	sb.WriteString("   log file = /var/log/samba/%m.log\n")
	sb.WriteString("   max log size = 1000\n")
	sb.WriteString("   dns proxy = no\n")
	// Keep the passdb and lock state on the mounted config directory so
	// provisioned accounts survive container restarts.
	sb.WriteString("   passdb backend = tdbsam:/etc/naslos/shares/private/passdb.tdb\n")
	sb.WriteString("   private dir = /etc/naslos/shares/private\n")
	sb.WriteString("   lock directory = /etc/naslos/shares/lock\n")
	sb.WriteString("   state directory = /etc/naslos/shares/state\n")
	sb.WriteString("   cache directory = /etc/naslos/shares/cache\n")
	sb.WriteString("   vfs objects = fruit streams_xattr\n")
	sb.WriteString("   fruit:time machine = yes\n")
	sb.WriteString("   fruit:model = MacSamba\n")
	sb.WriteString("   fruit:metadata = stream\n")
	sb.WriteString("   fruit:posix_rename = yes\n")
	sb.WriteString("   fruit:veto_appledouble = no\n")
	sb.WriteString("   fruit:nfs_aces = no\n")
	sb.WriteString("   fruit:wipe_intentionally_left_blank_rfork = yes\n")
	sb.WriteString("   fruit:delete_empty_adfiles = yes\n\n")

	for _, share := range m.shares {
		if share.Protocol != ProtocolSMB && share.Protocol != ProtocolAFP {
			continue
		}
		if !share.Enabled {
			continue
		}

		sb.WriteString(fmt.Sprintf("[%s]\n", share.Name))
		sb.WriteString(fmt.Sprintf("   path = %s\n", share.Path))
		sb.WriteString(fmt.Sprintf("   comment = %s\n", share.Description))

		if share.ReadOnly {
			sb.WriteString("   read only = yes\n")
		} else {
			sb.WriteString("   read only = no\n")
		}

		if share.Browseable {
			sb.WriteString("   browseable = yes\n")
		} else {
			sb.WriteString("   browseable = no\n")
		}

		// Client restriction (PF-H4): a share that names no hosts gets the node's
		// LAN CIDR, never "*". An operator opts into "*" explicitly by putting it
		// in allowedHosts.
		clients := effectiveClients(share)
		if !hasWildcard(clients) {
			sb.WriteString(fmt.Sprintf("   hosts allow = %s\n", strings.Join(clients, " ")))
			sb.WriteString("   hosts deny = all\n")
		}

		if access := accessList(share); len(access) > 0 {
			sb.WriteString(fmt.Sprintf("   valid users = %s\n", strings.Join(access, " ")))
		}

		if share.TimeMachine {
			sb.WriteString("   fruit:time machine = yes\n")
			sb.WriteString("   fruit:time machine max size = 1T\n")
		}

		// The session runs as the authenticated user's mapped uid (NSS/extrausers
		// maps the LDAP account), not as root: `force user = root` made every
		// write root-owned and defeated per-user access control (PF-H4).
		sb.WriteString("   create mask = 0660\n")
		sb.WriteString("   directory mask = 0770\n\n")
	}

	return sb.String()
}

// clientCIDR is the LAN the chart lets reach the NAS (networkPolicy.
// nfsClientCIDR, passed in as NASLOS_LAN_CIDR). It is the default client
// restriction for a share that names none.
func clientCIDR() string {
	return strings.TrimSpace(os.Getenv("NASLOS_LAN_CIDR"))
}

// effectiveClients returns the client list to render for a share: the share's own
// allowedHosts when it has any (which is the only place "*" can be opted into),
// otherwise the node's LAN CIDR, otherwise localhost only - fail closed rather
// than export to everyone (PF-H4).
func effectiveClients(share *Share) []string {
	if hosts := normalizeList(share.AllowedHosts); len(hosts) > 0 {
		return hosts
	}
	if cidr := clientCIDR(); cidr != "" {
		return []string{cidr}
	}
	return []string{"127.0.0.1/32"}
}

// hasWildcard reports whether a client list includes the explicit any-host entry.
func hasWildcard(clients []string) bool {
	for _, c := range clients {
		if strings.TrimSpace(c) == "*" {
			return true
		}
	}
	return false
}

// GenerateGaneshaConfig renders an NFS-Ganesha configuration for all enabled
// NFS shares.
//
// Ganesha (userspace) rather than /etc/exports is deliberate: Talos ships no
// kernel NFS server (only the nfs/nfs4 clients), so there is no nfsd to read
// /etc/exports and no rpcbind to register with. Ganesha serves NFSv4 on a
// single TCP port, which needs neither.
func (m *Manager) GenerateGaneshaConfig() string {
	var sb strings.Builder

	sb.WriteString("# Generated by Naslos - do not edit.\n")
	sb.WriteString("NFS_CORE_PARAM {\n")
	// NFSv4 only: locking is part of the protocol, so no lock manager RPC is
	// needed, and a single port means no rpcbind/portmapper. Serving v3 would
	// require rpcbind plus statd, which do not exist on Talos.
	sb.WriteString("    Protocols = 4;\n")
	sb.WriteString("    Enable_NLM = false;\n")
	sb.WriteString("    Enable_RQUOTA = false;\n")
	sb.WriteString("    NFS_Port = 2049;\n")
	// Clients mount the export by its pseudo path (host:/<name>) rather than by
	// its real path, so shares can be renamed on disk without changing what
	// clients mount.
	sb.WriteString("    mount_path_pseudo = true;\n")
	sb.WriteString("}\n\n")

	sb.WriteString("NFSv4 {\n")
	sb.WriteString("    Grace_Period = 10;\n")
	sb.WriteString("    Lease_Lifetime = 90;\n")
	sb.WriteString("}\n\n")

	// Kerberos is not configured, so tell Ganesha not to look for a keytab -
	// otherwise every start/reload logs machine-credential errors.
	sb.WriteString("NFS_KRB5 {\n")
	sb.WriteString("    Active_krb5 = false;\n")
	sb.WriteString("}\n\n")

	for _, share := range m.List() {
		if share.Protocol != ProtocolNFS || !share.Enabled {
			continue
		}
		sb.WriteString(ganeshaExport(share))
	}

	return sb.String()
}

// ganeshaExport renders one EXPORT block.
func ganeshaExport(share *Share) string {
	access := "RW"
	if share.ReadOnly {
		access = "RO"
	}
	// Root_Squash by default: an admin client's root is mapped to nobody, which
	// is the standard NFS posture. A share can opt out per-share when its data
	// is root-owned and an admin client legitimately needs to write it (PF-H4).
	squash := "Root_Squash"
	if share.NoRootSquash {
		squash = "No_Root_Squash"
	}
	clients := effectiveClients(share)

	var sb strings.Builder
	sb.WriteString("EXPORT {\n")
	sb.WriteString(fmt.Sprintf("    Export_Id = %d;\n", ganeshaExportID(share.Name)))
	sb.WriteString(fmt.Sprintf("    Path = %s;\n", share.Path))
	// The exported name clients mount: host:/<share name>.
	sb.WriteString(fmt.Sprintf("    Pseudo = /%s;\n", share.Name))
	sb.WriteString(fmt.Sprintf("    Access_Type = %s;\n", access))
	sb.WriteString(fmt.Sprintf("    Squash = %s;\n", squash))
	// AUTH_SYS: numeric uid/gid, the norm for a NAS. Deployments that need
	// Kerberos would add krb5 here.
	sb.WriteString("    SecType = sys;\n")
	sb.WriteString("    Protocols = 4;\n")
	sb.WriteString("    Transports = TCP;\n")
	sb.WriteString("    FSAL {\n")
	sb.WriteString("        Name = VFS;\n")
	sb.WriteString("    }\n")

	for _, host := range clients {
		host = strings.TrimSpace(host)
		if host == "" {
			continue
		}
		sb.WriteString("    CLIENT {\n")
		sb.WriteString(fmt.Sprintf("        Clients = %s;\n", host))
		sb.WriteString(fmt.Sprintf("        Access_Type = %s;\n", access))
		// Ganesha warns when a CLIENT block restricts protocols that are
		// not enabled globally, so state it explicitly here too.
		sb.WriteString("        Protocols = 4;\n")
		sb.WriteString(fmt.Sprintf("        Squash = %s;\n", squash))
		sb.WriteString("    }\n")
	}

	sb.WriteString("}\n\n")
	return sb.String()
}

// ganeshaExportID derives a stable Export_Id from the share name. Ganesha
// requires unique non-zero ids, and deriving (rather than numbering) keeps an
// export's identity stable when other shares are added or removed.
func ganeshaExportID(name string) int {
	h := fnv.New32a()
	_, _ = h.Write([]byte("nfs-export:" + name))
	return 1 + int(h.Sum32()%60000)
}

// AvailablePaths was removed deliberately: it listed every directory under the
// ZFS base, which includes plain directories on the node's ephemeral partition
// (e.g. /var/mnt/tank when "tank" is not a dataset). Offering those as share
// targets is how share data ended up outside ZFS, so the shareable paths now
// come from the agent's dataset list instead (see Server.datasetMountpoints).

// accessList builds the `valid users` entry for a share.
//
// Samba reads a bare name as a user and a name prefixed with '@' as a group, so
// ValidGroups entries are prefixed here. A '@' typed directly into ValidUsers
// is passed through unchanged, which keeps the raw field useful for groups that
// exist in the directory but are not mirrored yet.
//
// The list is empty when access is unrestricted (any authenticated user).
func accessList(share *Share) []string {
	seen := make(map[string]struct{})
	out := make([]string, 0, len(share.ValidUsers)+len(share.ValidGroups))

	add := func(entry string) {
		if entry == "" {
			return
		}
		if _, dup := seen[entry]; dup {
			return
		}
		seen[entry] = struct{}{}
		out = append(out, entry)
	}

	for _, u := range share.ValidUsers {
		u = strings.TrimSpace(u)
		if u == "" {
			continue
		}
		// An operator-typed '@group' is passed through as a group.
		if strings.HasPrefix(u, "@") {
			add(u)
			continue
		}
		// Strip a stray '@' elsewhere: Samba would read everything after it as
		// a group name, which would silently widen or break access.
		add(strings.ReplaceAll(u, "@", ""))
	}

	for _, g := range share.ValidGroups {
		g = strings.TrimPrefix(strings.TrimSpace(g), "@")
		if g == "" {
			continue
		}
		add("@" + g)
	}

	return out
}

// ConfigBundle is the set of rendered service configurations for the current
// share state. The API renders it and hands it to the privileged agent, which
// is the only component that can write to the Talos host filesystem.
type ConfigBundle struct {
	// SambaConf is the full smb.conf for SMB/Time Machine shares.
	SambaConf string `json:"sambaConf"`
	// GaneshaConf is the NFS-Ganesha configuration for NFS shares. Talos has no
	// kernel NFS server, so NFS is served by Ganesha (userspace), which reads
	// its own config format rather than /etc/exports.
	GaneshaConf string `json:"ganeshaConf"`
	// SambaUsers is the smbpasswd-format account file mirroring LDAP users
	// with their NT hashes (see SambaUserStore.RenderSMBPasswd).
	SambaUsers string `json:"sambaUsers"`
	// NSSPasswd / NSSGroup / NSSShadow are the extrausers-format files that
	// let the serving container resolve LDAP users through NSS, which Samba
	// needs in order to map a session to a UNIX uid.
	NSSPasswd string `json:"nssPasswd"`
	NSSGroup  string `json:"nssGroup"`
	NSSShadow string `json:"nssShadow"`
	// Revision changes whenever the share set changes, letting the servers
	// detect that a reload is needed.
	Revision string `json:"revision"`
	// ShareCount is the number of enabled shares represented above.
	ShareCount int `json:"shareCount"`
}

// NetBIOSName returns the name Samba advertises itself as, or "" to let Samba
// derive one from the host. Set via SMB_NETBIOS_NAME so it matches the name
// published over mDNS/WSD by the serving container — otherwise clients see the
// same server under two different names.
func (m *Manager) NetBIOSName() string {
	return sanitizeNetBIOSName(os.Getenv("SMB_NETBIOS_NAME"))
}

// sanitizeNetBIOSName enforces the NetBIOS rules: uppercase, no dots, at most
// 15 characters. Returns "" when there is nothing usable.
func sanitizeNetBIOSName(name string) string {
	name = strings.ToUpper(strings.TrimSpace(name))
	if name == "" {
		return ""
	}
	// A NetBIOS name is a single label; drop any domain part and characters
	// Samba would reject.
	if i := strings.IndexByte(name, '.'); i >= 0 {
		name = name[:i]
	}
	var b strings.Builder
	for _, r := range name {
		if (r >= 'A' && r <= 'Z') || (r >= '0' && r <= '9') || r == '-' || r == '_' {
			b.WriteRune(r)
		}
	}
	name = b.String()
	if len(name) > 15 {
		name = name[:15]
	}
	return name
}
func (m *Manager) RenderConfigBundle() ConfigBundle {
	enabled := 0
	for _, s := range m.shares {
		if s.Enabled {
			enabled++
		}
	}

	return ConfigBundle{
		SambaConf:   m.GenerateSambaConfig(),
		GaneshaConf: m.GenerateGaneshaConfig(),
		Revision:    m.revision(),
		ShareCount:  enabled,
	}
}

// revision derives a stable content hash of the enabled share set. Consumers
// compare it against the last applied revision to decide whether to reload.
func (m *Manager) revision() string {
	h := sha256.New()
	for _, s := range m.List() {
		fmt.Fprintf(h, "%s\x00%s\x00%s\x00%t\x00%t\x00%t\x00%t\x00%t\x00%s\x00%s\n",
			s.Name, s.Path, s.Protocol, s.Enabled, s.ReadOnly, s.Browseable,
			s.TimeMachine, s.NoRootSquash, strings.Join(s.AllowedHosts, ","), strings.Join(s.ValidUsers, ","))
	}
	return hex.EncodeToString(h.Sum(nil))[:16]
}
