apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: naslos
    app.kubernetes.io/part-of: naslos
    pod-security.kubernetes.io/enforce: privileged
