//! smb.conf / ganesha.conf rendering (port of `shares/config.go`).

use super::{Manager, Protocol, Share};

impl Manager {
    /// Render `smb.conf` for all enabled SMB/AFP shares.
    pub fn generate_samba_config(&self) -> String {
        let mut sb = String::new();
        sb.push_str("[global]\n");
        sb.push_str("   workgroup = NASLOS\n");
        sb.push_str("   server string = Naslos\n");
        sb.push_str("   security = user\n");
        if let Some(name) = self.netbios_name() {
            sb.push_str(&format!("   netbios name = {name}\n"));
        }
        sb.push_str("   map to guest = Never\n");
        sb.push_str("   server min protocol = SMB3\n");
        sb.push_str("   smb encrypt = desired\n");
        sb.push_str("   log file = /var/log/samba/%m.log\n");
        sb.push_str("   max log size = 1000\n");
        sb.push_str("   dns proxy = no\n");
        sb.push_str("   passdb backend = tdbsam:/etc/naslos/shares/private/passdb.tdb\n");
        sb.push_str("   private dir = /etc/naslos/shares/private\n");
        sb.push_str("   lock directory = /etc/naslos/shares/lock\n");
        sb.push_str("   state directory = /etc/naslos/shares/state\n");
        sb.push_str("   cache directory = /etc/naslos/shares/cache\n");
        sb.push_str("   vfs objects = fruit streams_xattr\n");
        sb.push_str("   fruit:time machine = yes\n");
        sb.push_str("   fruit:model = MacSamba\n");
        sb.push_str("   fruit:metadata = stream\n");
        sb.push_str("   fruit:posix_rename = yes\n");
        sb.push_str("   fruit:veto_appledouble = no\n");
        sb.push_str("   fruit:nfs_aces = no\n");
        sb.push_str("   fruit:wipe_intentionally_left_blank_rfork = yes\n");
        sb.push_str("   fruit:delete_empty_adfiles = yes\n\n");

        for share in self.list() {
            if share.protocol != Protocol::Smb && share.protocol != Protocol::Afp {
                continue;
            }
            if !share.enabled {
                continue;
            }

            sb.push_str(&format!("[{}]\n", share.name));
            sb.push_str(&format!("   path = {}\n", share.path));
            sb.push_str(&format!("   comment = {}\n", share.description));
            sb.push_str(if share.read_only {
                "   read only = yes\n"
            } else {
                "   read only = no\n"
            });
            sb.push_str(if share.browseable {
                "   browseable = yes\n"
            } else {
                "   browseable = no\n"
            });

            let clients = effective_clients(&share);
            if !has_wildcard(&clients) {
                sb.push_str(&format!("   hosts allow = {}\n", clients.join(" ")));
                sb.push_str("   hosts deny = all\n");
            }

            let access = access_list(&share);
            if !access.is_empty() {
                sb.push_str(&format!("   valid users = {}\n", access.join(" ")));
            }

            if share.time_machine {
                sb.push_str("   fruit:time machine = yes\n");
                sb.push_str("   fruit:time machine max size = 1T\n");
            }

            sb.push_str("   create mask = 0660\n");
            sb.push_str("   directory mask = 0770\n\n");
        }

        sb
    }

    /// Render an NFS-Ganesha configuration for all enabled NFS shares.
    pub fn generate_ganesha_config(&self) -> String {
        let mut sb = String::new();
        sb.push_str("# Generated by Naslos - do not edit.\n");
        sb.push_str("NFS_CORE_PARAM {\n");
        sb.push_str("    Protocols = 4;\n");
        sb.push_str("    Enable_NLM = false;\n");
        sb.push_str("    Enable_RQUOTA = false;\n");
        sb.push_str("    NFS_Port = 2049;\n");
        sb.push_str("    mount_path_pseudo = true;\n");
        sb.push_str("}\n\n");
        sb.push_str("NFSv4 {\n");
        sb.push_str("    Grace_Period = 10;\n");
        sb.push_str("    Lease_Lifetime = 90;\n");
        sb.push_str("}\n\n");
        sb.push_str("NFS_KRB5 {\n");
        sb.push_str("    Active_krb5 = false;\n");
        sb.push_str("}\n\n");

        for share in self.list() {
            if share.protocol != Protocol::Nfs || !share.enabled {
                continue;
            }
            sb.push_str(&ganesha_export(&share));
        }
        sb
    }

    /// The NetBIOS name Samba advertises, sanitised, or `None`.
    pub fn netbios_name(&self) -> Option<String> {
        let name = sanitize_netbios_name(&std::env::var("SMB_NETBIOS_NAME").unwrap_or_default());
        if name.is_empty() {
            None
        } else {
            Some(name)
        }
    }
}

fn client_cidr() -> String {
    std::env::var("NASLOS_LAN_CIDR")
        .unwrap_or_default()
        .trim()
        .to_string()
}

/// The client list to render: the share's own hosts, else the LAN CIDR, else
/// localhost (fail closed).
pub fn effective_clients(share: &Share) -> Vec<String> {
    let hosts = super::normalize_list(&share.allowed_hosts);
    if !hosts.is_empty() {
        return hosts;
    }
    let cidr = client_cidr();
    if !cidr.is_empty() {
        return vec![cidr];
    }
    vec!["127.0.0.1/32".to_string()]
}

fn has_wildcard(clients: &[String]) -> bool {
    clients.iter().any(|c| c.trim() == "*")
}

fn ganesha_export(share: &Share) -> String {
    let access = if share.read_only { "RO" } else { "RW" };
    let squash = if share.no_root_squash {
        "No_Root_Squash"
    } else {
        "Root_Squash"
    };
    let clients = effective_clients(share);

    let mut sb = String::new();
    sb.push_str("EXPORT {\n");
    sb.push_str(&format!(
        "    Export_Id = {};\n",
        ganesha_export_id(&share.name)
    ));
    sb.push_str(&format!("    Path = {};\n", share.path));
    sb.push_str(&format!("    Pseudo = /{};\n", share.name));
    sb.push_str(&format!("    Access_Type = {access};\n"));
    sb.push_str(&format!("    Squash = {squash};\n"));
    sb.push_str("    SecType = sys;\n");
    sb.push_str("    Protocols = 4;\n");
    sb.push_str("    Transports = TCP;\n");
    sb.push_str("    FSAL {\n");
    sb.push_str("        Name = VFS;\n");
    sb.push_str("    }\n");

    for host in &clients {
        let host = host.trim();
        if host.is_empty() {
            continue;
        }
        sb.push_str("    CLIENT {\n");
        sb.push_str(&format!("        Clients = {host};\n"));
        sb.push_str(&format!("        Access_Type = {access};\n"));
        sb.push_str("        Protocols = 4;\n");
        sb.push_str(&format!("        Squash = {squash};\n"));
        sb.push_str("    }\n");
    }

    sb.push_str("}\n\n");
    sb
}

/// A stable, unique non-zero Export_Id derived from the share name.
pub fn ganesha_export_id(name: &str) -> u32 {
    let mut hash: u32 = 0x811c9dc5;
    for b in format!("nfs-export:{name}").bytes() {
        hash ^= b as u32;
        hash = hash.wrapping_mul(0x01000193);
    }
    1 + (hash % 60000)
}

/// The `valid users` entry for a share: ValidUsers as-is (a `@`-prefixed entry
/// is a group), ValidGroups prefixed with `@`.
pub fn access_list(share: &Share) -> Vec<String> {
    let mut out = Vec::new();
    let mut seen = std::collections::HashSet::new();
    let mut add = |entry: String| {
        if entry.is_empty() || !seen.insert(entry.clone()) {
            return;
        }
        out.push(entry);
    };

    for u in &share.valid_users {
        let u = u.trim();
        if u.is_empty() {
            continue;
        }
        if u.starts_with('@') {
            add(u.to_string());
            continue;
        }
        add(u.replace('@', ""));
    }
    for g in &share.valid_groups {
        let g = g.trim().trim_start_matches('@');
        if g.is_empty() {
            continue;
        }
        add(format!("@{g}"));
    }
    out
}

/// Enforce the NetBIOS rules: uppercase, single label, ≤15 chars, A-Z0-9-_.
pub fn sanitize_netbios_name(name: &str) -> String {
    let name = name.trim().to_uppercase();
    if name.is_empty() {
        return String::new();
    }
    let name = match name.find('.') {
        Some(i) => &name[..i],
        None => &name[..],
    };
    let mut out = String::new();
    for r in name.chars() {
        if r.is_ascii_uppercase() || r.is_ascii_digit() || r == '-' || r == '_' {
            out.push(r);
        }
    }
    out.chars().take(15).collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::shares::{CreateShareRequest, Protocol};

    fn manager_with(shares: Vec<CreateShareRequest>) -> Manager {
        let dir = tempfile::tempdir().unwrap();
        let mut m = Manager::new("", "/var/mnt");
        for req in shares {
            m.create(&req).unwrap();
        }
        let _ = dir;
        m
    }

    fn req(name: &str, path: &str, protocol: Protocol) -> CreateShareRequest {
        CreateShareRequest {
            name: name.into(),
            path: path.into(),
            protocol,
            browseable: Some(true),
            enabled: Some(true),
            ..Default::default()
        }
    }

    #[test]
    fn samba_config_renders_shares_in_stable_order() {
        let m = manager_with(vec![
            req("zzz", "/var/mnt/tank/zzz", Protocol::Smb),
            req("aaa", "/var/mnt/tank/aaa", Protocol::Smb),
        ]);
        let conf = m.generate_samba_config();
        let a = conf.find("[aaa]").unwrap();
        let z = conf.find("[zzz]").unwrap();
        assert!(a < z, "shares must render sorted by name");
        assert!(conf.contains("   path = /var/mnt/tank/aaa\n"));
        assert!(conf.contains("   hosts deny = all\n"));
    }

    #[test]
    fn wildcard_host_disables_hosts_deny() {
        let mut r = req("pub", "/var/mnt/tank/pub", Protocol::Smb);
        r.allowed_hosts = vec!["*".into()];
        let m = manager_with(vec![r]);
        let conf = m.generate_samba_config();
        assert!(!conf.contains("hosts deny"));
        assert!(!conf.contains("hosts allow"));
    }

    #[test]
    fn valid_groups_are_at_prefixed() {
        let mut r = req("team", "/var/mnt/tank/team", Protocol::Smb);
        r.valid_groups = vec!["naslos_users".into()];
        r.valid_users = vec!["alice".into()];
        let m = manager_with(vec![r]);
        let conf = m.generate_samba_config();
        assert!(conf.contains("   valid users = alice @naslos_users\n"));
    }

    #[test]
    fn ganesha_export_block_and_root_squash() {
        let mut r = req("media", "/var/mnt/tank/media", Protocol::Nfs);
        r.no_root_squash = true;
        r.read_only = true;
        let m = manager_with(vec![r]);
        let conf = m.generate_ganesha_config();
        assert!(conf.contains("EXPORT {\n"));
        assert!(conf.contains("    Pseudo = /media;\n"));
        assert!(conf.contains("    Access_Type = RO;\n"));
        assert!(conf.contains("    Squash = No_Root_Squash;\n"));
        assert!(conf.contains("        Clients = 127.0.0.1/32;\n"));
    }

    #[test]
    fn ganesha_export_id_is_stable_and_nonzero() {
        let id = ganesha_export_id("media");
        assert!((1..=60000).contains(&id));
        assert_eq!(id, ganesha_export_id("media"));
    }

    #[test]
    fn netbios_name_is_sanitised() {
        assert_eq!(sanitize_netbios_name("naslos.local"), "NASLOS");
        assert_eq!(sanitize_netbios_name("my nas"), "MYNAS");
        assert_eq!(sanitize_netbios_name(""), "");
        assert_eq!(sanitize_netbios_name(&"a".repeat(30)).len(), 15);
    }

    #[test]
    fn injection_in_description_is_refused_at_create() {
        let mut r = req("evil", "/var/mnt/tank/evil", Protocol::Smb);
        r.description = "x\n[injected]".into();
        let mut m = Manager::new("", "/var/mnt");
        assert!(
            m.create(&r).is_err(),
            "a newline in a field must be refused"
        );
    }
}
